settings:
  telemetry_enabled: true
active_modules:
#  iso15118_2:
#    module: EvseV2G
#    config_module:
#      device: eth1
#      tls_security: allow
#      enable_sdp_server: false
#    connections:
#      security:
#        - module_id: evse_security
#          implementation_id: main
#  iso15118_20:
#    module: Evse15118D20
#    config_module:
#      device: eth1
#      tls_negotiation_strategy: ACCEPT_CLIENT_OFFER
#      enable_sdp_server: false
#    connections:
#      security:
#        - module_id: evse_security
#          implementation_id: main
#  iso_mux:
#    module: IsoMux
#    config_module:
#      device: eth1
#      tls_security: force
#    connections:
#      security:
#        - module_id: evse_security
#          implementation_id: main
#      iso2:
#        - module_id: iso15118_2
#          implementation_id: charger
#      iso20:
#        - module_id: iso15118_20
#          implementation_id: charger
#      ext2:
#        - module_id: iso15118_2
#          implementation_id: extensions
#      ext20:
#        - module_id: iso15118_20
#          implementation_id: extensions
  iso15118_charger:
    module: EvseV2G
    config_module:
      device: eth1
      supported_DIN70121: true
    connections:
      security:
        - module_id: evse_security
          implementation_id: main
  evse_security:
    module: EvseSecurity
    config_module:
      private_key_password: "123456"
#      csms_leaf_cert_directory: /mnt/user_data/etc/certs/client/csms
#      csms_leaf_key_directory:  /mnt/user_data/etc/certs/client/csms
#      secc_leaf_cert_directory: /home/futech/everest/etc/everest/certs_empty
#      secc_leaf_key_directory:  /home/futech/everest/etc/everest/certs_empty
#      v2g_ca_bundle: /mnt/user_data/etc/certs/ca/v2g/V2G_ROOT_CA.pem
#      mo_ca_bundle: /mnt/user_data/etc/certs/ca/mo/MO_ROOT_CA.pem
#      mf_ca_bundle: /mnt/user_data/etc/certs/ca/mf/MF_ROOT_CA.pem
#      csms_ca_bundle: /mnt/user_data/etc/certs/ca/csms/CSMS_ROOT_CA.pem
  yeti_driver:
    module: iLuchargeBSP
    config_module:
      baud_rate: 115200
      serial_port: /dev/everest/ilucharge1_serial
      reset_pin: 27
    connections:
      evse_manager:
      - module_id: evse_manager
        implementation_id: evse
  evse_manager:
    module: EvseManager
    telemetry:
      id: 1
    mapping:
      module:
        evse: 1
    config_module:
      connector_id: 1
      evse_id: 1
      connector_type: "cType2"
      has_ventilation: true
      evse_id: DE*PNX*E12345*1
      session_logging: true
      session_logging_xml: false
      session_logging_path: /tmp/logs/session
      charge_mode: DC
      hack_sleep_in_cable_check: 1
      hack_sleep_in_cable_check_volkswagen: 1
      hack_skoda_enyaq: true
      hack_pause_imd_during_precharge: false
      hack_allow_bpt_with_iso2: true
      hack_fix_hlc_integer_current_requests: true
      dc_isolation_voltage_V: 300
      disable_authentication: true
      cable_check_wait_below_60V_before_finish: false
      sae_j2847_2_bpt_enabled: true
      sae_j2847_2_bpt_mode: V2G
    connections:
      bsp:
      - module_id: yeti_driver
        implementation_id: board_support
      powermeter_car_side:
      - module_id: powermeter_dc
        implementation_id: main
      slac:
      - module_id: slac
        implementation_id: main
      hlc:
      - module_id: iso15118_charger
        implementation_id: charger
      powersupply_DC:
      - module_id: powersupply_dc
        implementation_id: main
      imd:
      - module_id: imd
        implementation_id: main
  slac:
    module: EvseSlac
    config_implementation:
      main:
        device: eth1
        number_of_sounds: 10
        sounding_attenuation_adjustment: -10
  auth:
    module: Auth
    config_module:
      connection_timeout: 10
      selection_algorithm: PlugEvents
    connections:
      token_provider:
      - module_id: token_provider_1
        implementation_id: main
      - module_id: token_provider_rfid
        implementation_id: main
      token_validator:
      - module_id: token_validator
        implementation_id: main
      evse_manager:
      - module_id: evse_manager
        implementation_id: evse
      kvs:
      - module_id: persistent_store
        implementation_id: main
  token_provider_1:
    module: DummyTokenProvider
    connections:
      evse:
      - module_id: evse_manager
        implementation_id: evse
  token_validator:
    module: DummyTokenValidator
    config_implementation:
      main:
        validation_result: Accepted
        validation_reason: Token seems valid
        sleep: 0.25
  energy_manager:
    module: EnergyManager
    config_module:
      schedule_interval_duration: 60
      schedule_total_duration: 1
      debug: false
    connections:
      energy_trunk:
      - module_id: grid_connection_point
        implementation_id: energy_grid
  grid_connection_point:
    module: EnergyNode
    config_module:
      fuse_limit_A: 32.0
      phase_count: 3
    connections:
      price_information: []
      energy_consumer:
        - module_id: evse_manager_sink
          implementation_id: energy_grid
  hmi:
    module: FutechHMI
    connections:
      evse_manager:
      - module_id: evse_manager
        implementation_id: evse
      futech_mqtt_interface:
      - module_id: futech_mqtt
        implementation_id: main
  api:
    module: API
    connections:
      evse_manager:
      - module_id: evse_manager
        implementation_id: evse
      evse_energy_sink:
        - module_id: evse_manager_sink
          implementation_id: external_limits
  error_history:
    module: ErrorHistory
    config_implementation:
      error_history:
        database_path: /tmp/error_history.db
  evse_manager_sink:
    module: EnergyNode
    mapping:
      module:
        evse: 1
    config_module:
      fuse_limit_A: 32.0
      phase_count: 3
    connections:
      energy_consumer:
        - module_id: evse_manager
          implementation_id: energy_grid
  setup:
    config_module:
      initialized_by_default: true
      localization: true
      online_check_host: lfenergy.org
      setup_simulation: true
      setup_wifi: true
    connections:
      store:
        - implementation_id: main
          module_id: persistent_store
    module: Setup
  persistent_store:
    module: PersistentStore
  futech_mqtt:
    module: FutechMqtt
    config_module:
      username: "123456789"
      password: xxxxxxxx
      server_address: solarlogs.be
      server_port: "1884"
      mode: manual
      vpn_enable_cmd: "sudo systemctl start openvpn-client@ilucharge2"
      vpn_disable_cmd: "sudo systemctl stop openvpn-client@ilucharge2"
    connections:
      hardware_info:
      - module_id: yeti_driver
        implementation_id: hardware_info
      powersupply_dc:
      - module_id: powersupply_dc
        implementation_id: main
      evse_board_support:
      - module_id: yeti_driver
        implementation_id: board_support
      relays:
      - module_id: yeti_driver
        implementation_id: relays
      sofar:
      - module_id: powersupply_sofar
        implementation_id: main
      evse_manager:
      - module_id: evse_manager
        implementation_id: evse
      slac:
      - module_id: slac
        implementation_id: main
  futech_thingsboard:
    module: FutechThingsboard
    config_module:
      token: "xxxxxxxx"
      server_address: thingsboard.solarlogs.be
      server_port: "1883"
    connections:
      hardware_info:
      - module_id: yeti_driver
        implementation_id: hardware_info
      powersupply_dc:
      - module_id: powersupply_dc
        implementation_id: main
      evse_board_support:
      - module_id: yeti_driver
        implementation_id: board_support
      relays:
      - module_id: yeti_driver
        implementation_id: relays
      sofar:
      - module_id: powersupply_sofar
        implementation_id: main
      evse_manager:
      - module_id: evse_manager
        implementation_id: evse
  system:
    module: System
  powersupply_dc:
    module: FutechMetaACDC
    connections:
      dcdc:
      - module_id: powersupply_futech
        implementation_id: main
      sofar:
      - module_id: powersupply_sofar
        implementation_id: main
  powersupply_futech:
    module: FutechDCDC
    config_module:
      fan_temperature_on: 35
      fan_temperature_hystersis: 2
    connections:
      fan:
      - module_id: yeti_driver
        implementation_id: fan
  powersupply_sofar:
    module: SofarHydInverterDriver
    config_module:
      inverter_device_id: 2
    connections:
      serial_comm_hub:
      - module_id: serial_comm_hub
        implementation_id: main
      evse_manager:
      - module_id: evse_manager
        implementation_id: evse
  imd:
    module: IMDSimulator
  serial_comm_hub:
    module: SerialCommHub
    config_implementation:
      main:
        serial_port: /dev/everest/rs485_1
        rxtx_gpio_chip: gpiochip0
        rxtx_gpio_line: 16
        rxtx_gpio_tx_high: true
        baudrate: 9600
        parity: 0
  powermeter_dc:
    module: AcrelPowermeterDC
    config_implementation:
      main:
        powermeter_device_id: 1
    connections:
      serial_comm_hub:
      - module_id: serial_comm_hub
        implementation_id: main
  token_provider_rfid:
    config_implementation:
      main:
        serial_port: /dev/everest/rfid_1
    connections: {}
    module: PN532TokenProvider
x-module-layout: {}
